package MyTestPreparation01;

public class T66_Exceptions {
    public static void main(String[] args) {
        try {
//            int a = 5/3.5;
        }  catch (ArithmeticException e){
            System.out.println("This is not possible");
        }
    }
}

/*
What will happen if we run this code?
Compile time error
Runtime exception
Will not print anything
This is not possible


*/
